### ISSUE TITLE
Show Pull Requests

### ISSUE THREAD

**Issue by jernejk** [panuoksala/streamdeck-azuredevops-plugin#6]
As a tech lead, I want to see pull requests.

Ideas for the button:
- Show number of active PR
- Show number of active PR without reviews
- Show the number of PRs require actions (review, build failed, requires assigning a task, etc.)
- Each of the above would have the option of "Team" and "My" PRs

Action:
- Update
- Open in browser
- Restart build?
- Complete PR? (if only one is present)

**Comment by jernejk** [comment]
I might take this one in the coming month.
It's an semi hourly ritual to check PRs and this can save me a trip.

**Comment by panuoksala** [comment]
The number of PR's / number of PR's waiting for me would be cool.
Button should maybe just open browser to PR's list page.

Settings for that is a bit harder, because it is specific for this feature... Maybe investigate if the settings page could be specific for actions. Like now we have build/release => add pull requests and if you select that the rest of settings page will change specific to PR's

**Comment by panuoksala** [comment]
I think I will implement this, so that you could open list of waiting PR's directly from Stream Deck. I wonder if there is API to receive all open PR's?

**Comment by panuoksala** [comment]
Implemented ability to check how many active pull requests are waiting.
Added button action to navigate into active pull request page
Added button action to navigate into new pull request page
